# Generated by Django 4.2.3 on 2023-07-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='', max_length=20)),
                ('temp', models.FloatField()),
                ('wind_speed', models.IntegerField()),
                ('weather_description', models.CharField(default='', max_length=100)),
                ('requst_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-requst_date'],
            },
        ),
    ]
